### ISSUE TITLE
Feature request: Package SideQuest as a Flatpak

### ISSUE THREAD

**Issue by garrhow** [SideQuestVR/SideQuest#184]
Packaging SideQuest as a Flatpak (and ideally distributing it through Flathub) would be make the program more accessible to Linux users regardless of their distribution, and would greatly simplify the installation process.

I have created the following repository as a showcase of a working Flatpak of SideQuest.
https://github.com/garrhow/com.sidequestvr.SideQuest

**Comment by sidequestlegend** [comment]
This is great an i really appreciate the time and effort you have put in here. The problem is our capacity is limited and we don't have the resources to maintain this or other package manager submissions and we cant rely on the consistency of user contributions like this one. 

Once again, thanks for your effort here.
