### ISSUE TITLE
Bug: App crashes when uploading file with Korean name

### ISSUE THREAD

**Issue by atgambardella** [SideQuestVR/SideQuest#98]
When sending a file with a name in Korean to the Quest, this error shows up endlessly, requiring one to kill the program with task manager:

![error](https://user-images.githubusercontent.com/1356657/100176914-fe512600-2ec8-11eb-91a4-20590308d125.PNG)

Renaming the file using only Latin characters fixes the error, but if Korean filenames cannot be supported, this should fail more gracefully

**Comment by sidequestlegend** [comment]
Hi there, it looks like this is caused by a different error as the above screenshot is what is seen when the connection drops between the headset and PC while a transfer is underway. You are right this error should be handled more gracefully. 

It looks like copying files with these filenames is not currently supported by ADB - https://stackoverflow.com/a/15519595. Some workarounds include copying or renaming the file but those also introduce their own complications. The truth here is that it may make more sense to rename these files before you transfer them.

**Comment by bricefriha** [comment]
@sidequestlegend What kind of complications would that include? 🙂

**Comment by sidequestlegend** [comment]
Well I guess I meant needing to rename all files before/after transfer or detect files with unsupported characters and only rename those before transfer. All of which require either altering the files as they are or making copies which can then require more storage space.

**Comment by bricefriha** [comment]
> Well I guess I meant needing to rename all files before/after transfer or detect files with unsupported characters and only rename those before transfer. All of which require either altering the files as they are or making copies which can then require more storage space. 

Good point,
There is also the option of telling the user that the app doesn't support these types of characters via a prompt.

But I don't see a huge issue if we rename all files by a Guid for example.
Aside from the issue of the storage space.
How big these files can be?

**Comment by bricefriha** [comment]
Sounds like a good idea!

**Comment by bricefriha** [comment]
@sidequestlegend I'd be glad to help on that task if you need 😉

**Comment by sidequestlegend** [comment]
Hey I'm always open to a PR! Appreciate it!
